practice/practice2/polls/urls.py
from django.urls import path
from polls import views

app_name = 'polls'

# path(url, viewe함수)
urlpatterns = [
    path('list', views.list, name='list'),
    path('<int:question_id>/vote_form', views.vote_form, name='vote_form'),
    path('vote', views.vote, name='vote'),
    path('<int:question_id>/result', views.result, name='result')
]

practice/practice2/polls/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField()

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

practice/practice2/polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from polls.models import Question, Choice



# Create your views here.

def list(request):
    question_list = Question.objects.all()
    return render(request, "polls/list.html", {'q_l':question_list})


def vote_form(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        return render(request, 'polls/vote_form.html', {'selected_question':question})
    except Exception as e:
        return list(request)


def vote(request):
    # 요청 파라미터 조회
    question_id = request.POST.get('question_id')
    choice_id = request.POST.get('choice')

    # 요청 파라미터 검증
    if not choice_id:
        question = Question.objects.get(pk=question_id)
        return render(request, 
                    'polls/vote_form.html', 
                    {'selected_question':question, 'error_messsage':"보기를 선택하세요."})

    # 요청 처리 - Business Logic
    selected_choice = Choice.objects.get(pk=choice_id)
    selected_choice.votes += 1
    selected_choice.save()

    return_url = reverse("polls:result", args=[question_id])
    print(return_url)
    return redirect(return_url)



def result(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, 'polls/result.html', {'selected_question':question})

practice/practice2/polls/templates/polls/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>설문 리스트</title>
</head>
<body>
    <ul>
        {% for question in q_l %}
        <li>
            <!--url 형식: polls/question 번호/vote_form-->
            <a href = '/polls/{{question.pk}}/vote_form'>
            {{question.question_text}}<font size = "1">{{question.pub_date|date:'Y-m-d'}}</font>
            </a>
        </li>
        {% endfor %}
        
    </ul>
</body>
</html>

practice/practice2/polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>투표 결과</title>
</head>
<body>
    <h1>{{selected_question.question_text}}</h1>
    작성일:{{selected_question.pub_date|date:'Y-m-d'}}
    <ol>
        {% for choice in selected_question.choice_set.all %}
            <li>{{choice.choice_text}}-{{choice.votes}}</li>
        {% endfor %}

    </ol>
<a href="{% url "polls:list" %}">질문목록</a>

</body>
</html>

practice/practice2/polls/templates/polls/vote_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>설문 투표</title>
</head>
<body>
질문:{{selected_question.question_text}}  <!--selected_question은 views.py에서 키값-->

<form action='{% url "polls:vote" %}' method='post'>
    {% csrf_token %}
    <input type="hidden" name="question_id" value="{{question.pk"}}>

    {% for choice in selected_question.choice_set.all %}
    <input type="radio" id='id_{{choice.pk}}' 
            name='choice' value={{choice.pk}}>
    <label for="id_{{choice.pk}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <br>
    <br>
    <input type="submit" value='제출'>
    <input type="reset" value='초기화'>
    <br>
    <br>
    {%if error_message %}
    <div style="color: red">{{error_message}}</div>
    {% endif %}
    
</form>
</body>
</html>