form_exam/exam/urls.py
from django.urls import path

from exam import views

app_name = 'exam'

urlpatterns = [
    path('join', views.JoinView.as_view(), name='join'),
    path('<int:pk>/detail', views.UserDetailView.as_view(), name='detail'),

    # /exam/2/detail
]

form_exam/exam/models.py
from django.db import models

# Create your models here.
# 사용자 - User
class User(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
        return "{}-{}".format(self.name, self.age)


# 관심언어
class InterestLanguage(models.Model):
    language = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.language    


# 코드 테이블
class Code(models.Model):
    code = models.CharField(max_length=100, primary_key=True)
    code_text = models.CharField(max_length=200)
    code_category = models.CharField(max_length=100)

    def __str__(self):
        return self.code_text

form_exam/exam/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View, DetailView

from exam.models import User, InterestLanguage, Code
# Create your views here.
# 등록 폼 + 등록 처리 View
class JoinView(View):
    # 입력 폼 요청
    def get(self, request, *args, **kwargs):
        lang = Code.objects.filter(code_category = 'language')
        return render(request, 'exam/join_form.html', {'lang':lang}) 

    def post(self, request, *args, **kwargs):
        # 1. 요청 파라미터 조회
        name = request.POST.get('name')    # 문자열
        age = request.POST.get('age')    # 문자열
        interest_language_list = request.POST.getlist('interest_language')   # 리스트, 같은 이름으로 여러개 넘어올 때
        print(name, age, interest_language_list)
        # 2. 요청 파라미터 검증
        if not (name and age and interest_language_list):
            lang = Code.objects.filter(code_category = 'language')
            return render(request, 'exam/join_form.html', {"error_message":"이름, 나이, 관심언어를 입력하세요.", "lang":lang})

        # 3. 검증 통과 -> 처리 - 저장
            # User insert
        user = User(name=name, age=age)
        user.save()    # insert. insert 후에 pk를 user 객체에 할당

        for interest in interest_language_list:
            i_lang = InterestLanguage(language = interest, user= user)    # models.py 참고
            i_lang.save()
        
            # 4. 응답 - render() / redirect()-변경(insert, update, delete)
        return redirect(reverse('exam:detail', args=[user.pk]))   # name을 가진 url 가져오기


# 한 User 정보 조회 view
class UserDetailView(DetailView):
    model = User
    template_name = 'exam/user_detail.html'

    # {object:조회한 user} {user:User}

form_exam/exam/templates/exam/join_form.html
{% extends 'base.html'%}
{% block title%}등록{% endblock title%}

{% block contents%}

{% if error_message != None%}
<span style='color:red'>{{error_message}}</span>
{% endif%}
<form action="{% url 'exam:join' %}" method='post'>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">이름</label>
        <input type="text" class="form-control" id="id_name" name='name'>
    </div>
    <div class="form-group">
        <label for="id_age">나이</label>
        <input type="text" class="form-control" id="id_age" name='age'>
    </div>
    <p>관심언어</p>
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" name='interest_language' id="inlineCheckbox1" value="python">
        <label class="form-check-label" for="inlineCheckbox1">파이썬</label>
    </div>
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" name='interest_language' id="inlineCheckbox2" value="Java">
        <label class="form-check-label" for="inlineCheckbox2">자바</label>
    </div>
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" name='interest_language' id="inlineCheckbox3" value="C">
        <label class="form-check-label" for="inlineCheckbox3">C 언어</label>
    </div>
    <hr>
    {% for code in lang %}
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" name='interest_language' id="{{code.pk}}" value="{{code.pk}}">
        <label class="form-check-label" for="{{code.pk}}">{{code.code_text}}</label>
    </div>
    {% endfor %}

    <p>
        <br><button class='btn btn-primary' type='submit'>등록</button>
    </p>    
</form>
{% endblock contents%}

form_exam/exam/templates/exam/user_detail.html
{% extends 'base.html' %}

{% block title %} 사용자 정보 {% endblock title %}

{% block contents %}
ID: {{user.pk}} <br>
이름: {{user.name}} <br>
나이: {{user.age}} <br>
관심언어: {{ user.interestlanguage_set.all|join:", "}}
{% endblock contents %}