form_exam2/exam/urls.py
from django.urls import path
from exam import views

app_name = 'exam'

urlpatterns = [
    path('register', views.RegisterView.as_view(), name = 'register'),
    path('list', views.UserList.as_view(), name='userlist'),
    path('<int:pk>/detail', views.UserDetail.as_view(), name='userdetail'),
]

form_exam2/exam/models.py
from django.db import models

# Create your models here.

# Code테이블 연동 모델
class Code(models.Model):
    code = models.CharField(max_length=100, primary_key=True)    # 기본적으로 primary key 값을 name으로
    code_text = models.CharField(max_length=100)                 # str이 반환해주는 값을 label
    code_category = models.CharField(max_length=200)

    def __str__(self):
        return self.code_text

# User 테이블 연동 모델
class User(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()

    def __str__(self):
        return self.name

class InterestLanguage(models.Model):
    language = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.language

form_exam2/exam/forms.py
from django import forms

from exam import models

# Form 클래스 작성: 요청 form의 입력 양식들을 관리하는 클래스.
# 입력받는 템플릿 작성, 전송된 요청파라미터를 읽고 검증하는 작업을 담당
# Form 클래스 - <form>, form 태그 하나당 하나씩
# 클래스 변수 - <input>, <select>, <textarea>: 한 개의 입력폼

class RegisterForm(forms.Form):
    # 클래스 변수: 변수명-name, 값-입력양식타입 객체
    # CharField - 문자열 입력받는 input 양식. - 기본 위젯:<input type=text>
    name = forms.CharField(max_length=100, label='사용자 이름', widget=forms.TextInput(attrs={'class':'form-control'})) # requered 디폴트 True
    age = forms.IntegerField(label='나이', widget=forms.NumberInput(attrs={'class':'form-control'}))
    
    # 원소(value, label)
    CHOICES = [
        ('Python', '파이썬'),
        ('Java', '자바'),
        ('Ruby', '루비')
    ]
    # ChoiceField - 여러개중에 한 개 선택
    # MultipleChoiceField - 여러개 중에 여러개 선택
    # 선택 항목을 리스트로 묶어서 전달.
    # 기본 위젯: select(radio-단일선택, checkbox-다중선택)

    # interest_language = forms.MultipleChoiceField(label='관심언어', 
    #                                             choices=CHOICES,
    #                                             widget=forms.CheckboxSelectMultiple)


    # modelChoiceField, ModelMultipleChocieField - 선택항목을 Model(데이터베이스)에서 가져온다.
    # value:PK 컬럼값, label:str()로 반환된 값.
    interest_language = forms.ModelMultipleChoiceField(label='취미',
                                                    widget=forms.CheckboxSelectMultiple(attrs={'class':'form-check form-check-inline'}),
                                                    required=True,                                                                                            
                                                    queryset=models.Code.objects.filter(code_category='hobby'))

    # 사용자 정의 폼 검증 코드
    # 각 Field에 선언된 검증을 마친 다음에 호출된다.

    # 직접 정하는 검증 조건을 메소드로 만들어 준다.
    def clean(self):
        # 기본 검증을 통과한 요청 파라미터 조회             
        cleaned_data = super().clean()
        print(type(cleaned_data), cleaned_data)

        # 나이 > 0, 이름은 2글자 이상
        if cleaned_data.get('age') <= 0:
            # 에러 메세지 추가
            self.add_error("age", "나이는 1 이상을 넣으세요.")    # 입력태그의 name, 에러메세지
            
        if len(cleaned_data.get('name')) < 2:
            self.add_error('name', '이름은 2글자 이상 넣으세요.')

form_exam2/exam/views.py
from django.shortcuts import render
from django.views.generic import FormView, ListView, DetailView
from django.urls import reverse_lazy

from exam.forms import RegisterForm
from exam import models

# Create your views here.
# 등록처리 View - 등록양식응답, 등록처리 => Form Class 이용:FormView 상속 받기
class RegisterView(FormView):
    template_name = 'exam/register_form.html'    # 입력양식 템플릿 지정. 입력폼 위치를 알려줌.
    form_class = RegisterForm
    success_url = reverse_lazy('exam:userlist')   # 등록 처리 후 이동할 url(리다이렉트 방식 이용). 등록 성공했을 때 이동할 위치.

    # 요청파라미터를 처리하는 비즈니스 로직 작성.
    # 호출시점: 요청파라미터 검증 끝나고 에러메세지가 없을 때 호출.
    def form_valid(self, form):    # form: 검증 끝난 요청파라미터.
        name = form.data.get('name')
        age = form.data.get('age')
        interest_language = form.data.getlist('interest_language')
        user = models.User(name=name, age=age)
        user.save()

        for lang in interest_language:
            language = models.InterestLanguage(language=lang, user=user)
            language.save()

        return super().form_valid(form)

class UserList(ListView):
    template_name = 'exam/user_list.html'    
    model = models.User
    paginate_by = 5    # 한 페이지에 보여질 데이터 수

    # template에 전달할 context 변수 생성
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        page_numbers_range = 5    # 페이지 그룹의 페이지 개수
        paginator = context.get('paginator')
        max_page = paginator.num_pages    # 총 페이지 수

        page_tmp = self.request.GET.get('page')    # self.request : 요청정보인 HttpRequest 객체 반환
        current_page = int(page_tmp if page_tmp else 1)
        # url?page=3    exam/list

        start_index = int((current_page-1)/page_numbers_range)*page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index > max_page:
            end_index = max_page
        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        print(context)

    


        return context




class UserDetail(DetailView):
    template_name = 'exam/user_detail.html'
    model = models.User

form_exam2/exam/templates/exam/register_form.html
{% extends 'base.html' %}

{% block title %}등록폼{% endblock title%}

{% block contents %}
<h2>사용자 등록</h2>

<!--
    field.name: form의 name에 지정하는 값 반환.
    field.id_for_label: label 값을 반환.
    field.error: 검증 에러메세지가 있는 경우 반환.
-->

<form action = '{% url "exam:register" %}' method='post'>
    {% csrf_token %}    
    {% for field in form %}
        {% if field.name != 'interest_language' %}
        <!-- 일반 폼-이름/나이 -->
        <div class='form-group'>
            <label for='{{field.id_for_label}}'>{{field.label}}</label>
            {{field}}
        </div>
            {% if field.errors%}
                <span style="color:red">{{field.errors}}</span>
            {% endif %}
        {% else %}
        <!-- 체크박스-관심언어 -->
        <p>관심언어</p>
        <div class='form-check'>
            {% for item in field %}
                {{item}}
            {% endfor %}
        </div>
            {% if field.errors%}
                <span style="color:red">{{field.errors}}</span>
            {% endif %}
        {% endif %}
    {% endfor %}
    <input type="submit" value='등록' class="btn btn-primary">
</form>
{% endblock contents %}

form_exam2/exam/templates/exam/user_detail.html
{% extends 'base.html' %}

{% block title %}사용자 상세정보{% endblock title %}

{% block contents %}
<table class='table'>
    <tr>
        <th>ID</th>
        <td>{{user.pk}}</td>

    </tr>
    <tr>
        <th>이름</th>
        <td>{{user.name}}</td>
    </tr>
    <tr>
        <th>나이</th>
        <td>{{user.age}}</td>
    </tr>
    <tr>
        <th>관심사항</th>
        <td>{{user.interestlanguage_set.all|join:','}}</td>
    </tr>
</table>
{% endblock contents %}

form_exam2/exam/templates/exam/user_list.html
{% extends 'base.html' %}

{% block title%}사용자 목록{% endblock title%}

{% block contents %}
<h2>사용자 목록</h2>
<table class = 'table table-bordered'>
    <thead>
        <th>ID</th>
        <th>이름</th>
        <th>나이</th>
    </thead>
    <tbody>
        {% for user in user_list %}
        <tr>
            <td>{{user.pk}}</td>
            <td>
                <a href="{% url 'exam:userdetail' user.pk %}">{{user.name}}</a>
            </td>
            <td>{{user.age}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Pagination -->
{# paginator : Paginator 객체 참조, page_obj: Page 객체 참조 #}
{# 페이징 관련 정보(객체)가 있는지 여부 #}
{% if is_paginated %}
<nav>
<ul class = 'pagination'>
<!-- 이전 페이지 관련 작업 -->
{% if page_obj.has_previous %}
    <li class='page-item'><a class="page-link" href="?/page=1">처음</a></li>
    <li class='page-item'><a class="page-link" href="?/page={{page_obj.previous_page_number}}">이전</a></li>

{% else %}    
    <li class='page-item'><span class='page-link'>처음</span></li>
    <li class='page-item'><span class='page-link'>이전</span></li>
{% endif %}



<!-- page group의 페이지 번호 출력 
page_obj.number: 현재 페이지-->
{% for page in page_range %}
    <li class='page-item'>
    {% if page == page_obj.number %}   <!--현재 페이지인지 확인-->
        <span class='page-link'>{{page}}</span>
    {% else %}
        <a class="page-link" href="?page={{page}}">{{page}}</a>
    {% endif %}
    </li>   
{% endfor %}





<!-- 다음 페이지 관련 작업 -->
{% if page_obj.has_next %}
    <li class="page-item">
        <a class='page-link' href="?page={{page_obj.next_page_number}}">다음</a>
    </li>
    <li class="page-item">
        <a class='page-link' href="?page={{paginator.num_pages}}">마지막</a>
    </li>

{% else %}
    <li class="page-item">
        <span class='page-link'>다음</span>
    </li>
    <li class="page-item">
        <span class='page-link'>마지막</span>
    </li>

{% endif %}

</ul>
</nav>


{% endif %}

{% endblock contents %}